import{A as E,S as O,i as c}from"./assets/vendor-db5ad915.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P=document.querySelector(".form"),p=document.querySelector(".input-name"),l=document.querySelector(".loader"),h=document.querySelector(".gallery"),m=document.querySelector(".load-btn");let u="",n=0,d=0,f=1;const y=E.create({baseURL:"https://pixabay.com",params:{key:"42444486-bc4896f356324bce186cf1418",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1}});let $=new O(".image-link",{captionsData:"alt",captionDelay:250});async function x(o){o.preventDefault();const t=p.value.trim();if(t===""){c.show({title:"Error",message:"Please enter a search query"});return}u=t,p.value="",h.innerHTML="",f=1,n=0,g(),l.classList.add("visible");try{const i=(await y.get("/api/",{params:{q:u}})).data;d=i.totalHits,n=b(i.hits,d,n)}catch(s){console.log("Error fetching data:",s),c.show({title:"Error",message:"Oops, something went wrong"})}finally{l.classList.remove("visible")}}async function C(){g(),l.classList.add("visible");try{const t=(await y.get("/api/",{params:{q:u,page:f+=1}})).data;d=t.totalHits,n=b(t.hits,d,n),M()}catch(o){console.log("Error fetching data:",o),c.show({title:"Error",message:"Oops, something went wrong"})}finally{l.classList.remove("visible")}}function b(o,t,s){if(o.length===0){c.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",messageSize:"25"});return}return o.forEach(i=>{const{webformatURL:e,largeImageURL:r,tags:a,likes:v,views:w,comments:L,downloads:S}=i,q=k(e,r,a,v,w,L,S);h.insertAdjacentHTML("beforeend",q)}),s+=o.length,$.refresh(),H(s,t),s}function k(o,t,s,i,e,r,a){return`<li class="photo">
  <div class="photo-card">
    <a class="image-link" data-lightbox="image" href="${t}">
    <img class="gallery-image" data-source="${t}"  src="${o}" alt="${s}"></img>
    </a>
    </div>
      <div class="description">
        <p class="description-item"> Likes ${i}</p>
        <p class="description-item"> Views ${e}</p>
        <p class="description-item"> Comments ${r}</p>
        <p class="description-item"> Downloads ${a}</p>

    </div>
  </li>`}function H(o,t){if(o>=t){c.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#125487",messageColor:"white",messageSize:"25"}),g();return}else B()}function M(){const o=document.querySelector(".photo").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}function B(){m.style.visibility="visible"}function g(){m.style.visibility="hidden"}P.addEventListener("submit",x);m.addEventListener("click",C);
//# sourceMappingURL=commonHelpers.js.map
